import h5py
import argparse
import matplotlib.pyplot as plt
import numpy as np
import os

def inspect_dataset(dataset_dir, episode_idx):
    dataset_path = os.path.join(dataset_dir, f'episode_{episode_idx}.hdf5')
    
    if not os.path.exists(dataset_path):
        print(f"Error: File does not exist: {dataset_path}")
        return

    print(f"Inspecting: {dataset_path}")
    
    with h5py.File(dataset_path, 'r') as root:
        # 1. Print File Structure
        print("\n--- HDF5 Structure ---")
        def print_attrs(name, obj):
            # Indent based on hierarchy depth
            indent = '    ' * (name.count('/') + 1)
            print(f"{indent}{name}")
            
            # Print attributes
            for key, val in obj.attrs.items():
                print(f"{indent}  [Attr] {key}: {val}")
            
            # Print dataset details
            if isinstance(obj, h5py.Dataset):
                print(f"{indent}  Shape: {obj.shape}")
                print(f"{indent}  Type:  {obj.dtype}")

        root.visititems(print_attrs)

        # 2. Extract Data
        qpos = root['/observations/qpos'][()]
        qvel = root['/observations/qvel'][()]
        action = root['/action'][()]
        
        # 3. Print Statistics
        print("\n--- Statistics ---")
        print(f"Timesteps: {qpos.shape[0]}")
        print(f"Action stats | Min: {action.min():.4f}, Max: {action.max():.4f}, Mean: {action.mean():.4f}")
        print(f"Qpos stats   | Min: {qpos.min():.4f}, Max: {qpos.max():.4f}")
        
        # 4. Plot Trajectories (Joint Positions, Velocities, Actions)
        print("\n--- Plotting Trajectories (Close window to continue to video) ---")
        fig, axs = plt.subplots(3, 1, figsize=(10, 8), sharex=True)
        
        axs[0].plot(qpos)
        axs[0].set_title('Joint Positions (qpos)')
        axs[0].grid(True)
        
        axs[1].plot(qvel)
        axs[1].set_title('Joint Velocities (qvel)')
        axs[1].grid(True)
        
        axs[2].plot(action)
        axs[2].set_title('Actions')
        axs[2].set_xlabel('Time Step')
        axs[2].grid(True)
        
        plt.tight_layout()
        plt.show()

        # 5. Visualize Video
        image_grp = root['/observations/images']
        cam_names = list(image_grp.keys())
        
        if not cam_names:
            print("No images found in dataset.")
            return

        print(f"\n--- Playing Video for cameras: {cam_names} ---")
        
        # Load images into memory
        video_data = {cam: image_grp[cam][()] for cam in cam_names}
        num_steps = list(video_data.values())[0].shape[0]
        num_cams = len(cam_names)

        # Setup plot for video playback
        fig, axes = plt.subplots(1, num_cams, figsize=(4 * num_cams, 3))
        if num_cams == 1:
            axes = [axes]

        displays = []
        for i, cam in enumerate(cam_names):
            axes[i].set_title(f"{cam} ({video_data[cam].shape})")
            axes[i].axis('off')
            # Initialize with the first frame
            displays.append(axes[i].imshow(video_data[cam][0]))

        plt.tight_layout()
        
        # Playback loop
        for t in range(num_steps):
            for i, cam in enumerate(cam_names):
                displays[i].set_data(video_data[cam][t])
            
            plt.pause(0.01) # Simple pause for animation speed
            
        print("Done.")

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Inspect HDF5 data generated by record_sim_episodes.py")
    parser.add_argument('--dataset_dir', action='store', type=str, default='/mnt/Ego2Exo/pick_teleop_4/todo/reduced/to/', help='Directory containing the episode_*.hdf5 files')
    parser.add_argument('--episode_idx', action='store', type=int, default=0, help='Index of the episode to inspect')
    
    args = parser.parse_args()
    inspect_dataset(args.dataset_dir, args.episode_idx)